<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Peeklism.App</RootNamespace>
    <ApplicationIcon>..\..\docs\assets\peeklism.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <PublishProfile>win-x64.pubxml</PublishProfile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Peeklism.Core\Peeklism.Core.csproj" />
    <Content Include="..\..\docs\assets\peeklism.ico" Link="Assets\Peeklism.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\docs\assets\peeklism-logo-concept-v1.png" Link="Assets\Peeklism.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
